# This workflow deploys the package on release.

name: Deploy

on:
  release:
    types: [published]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
    - name: Test with pytest
      env:
        TEST_ACCOUNT: ${{ secrets.TEST_ACCOUNT }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_ELECTRIC_NUMBER : ${{ secrets.TEST_ELECTRIC_NUMBER }}
      run: |
        python -m pytest ./tests
  deploy:
    needs: pytest
    environment: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}